export const contributeUI = {
  en: {
    // Meta
    'contribute.meta.title': 'I Want to Contribute — Ethiopia.md',
    'contribute.meta.description':
      'No programming skills needed. You can help the world understand Ethiopia',

    // Hero Section
    'contribute.hero.title': 'I Want to Contribute ✋',
    'contribute.hero.subtitle':
      'No programming skills needed. Your Ethiopia stories are the most valuable content.',
    'contribute.hero.note.html':
      'Current website content is initially generated by AI, expecting everyone to join forces to make information more complete and accurate!<br />If you have any questions, please feel free to <a href="mailto:getachewnatnael55@gmail.com" style="color: #ABC468;">contact us</a>. Thank you for your thoughtful feedback!',

    // How It Works Section
    'contribute.how.title': '🗺️ First, understand how this website works',
    'contribute.how.language.icon': '📁',
    'contribute.how.language.title': 'Language Toggle',
    'contribute.how.language.desc.html':
      'Toggle between <strong>Chinese</strong> and <strong>English</strong> in the top-right corner. Chinese is the primary content (SSOT), English is being translated continuously.',
    'contribute.how.language.code.html':
      'ethiopia.md/ → Chinese<br />ethiopia.md/en/ → English',
    'contribute.how.md.icon': '📝',
    'contribute.how.md.title': '.md Button',
    'contribute.how.md.desc.html':
      "The floating <strong>.md</strong> button in the bottom-right corner of each page shows the original Markdown file. All Ethiopia.md content is plain text Markdown — that's where the .md domain comes from.",
    'contribute.how.graph.icon': '🕸️',
    'contribute.how.graph.title': 'Knowledge Graph',
    'contribute.how.graph.desc':
      'The "Graph" link in the navigation leads to an interactive knowledge network diagram. Drag to explore connections between 12 aspects.',
    'contribute.how.ai.icon': '🤖',
    'contribute.how.ai.title': 'AI-Friendly',
    'contribute.how.ai.desc.html':
      'All content is fully open to AI crawlers (<a href="/robots.txt">robots.txt</a>, <a href="/llms.txt">llms.txt</a>). Feel free for ChatGPT / Claude / Gemini to cite.',

    // Roles Section
    'contribute.roles.title': "Your expertise is Ethiopia's needed strength",
    'contribute.roles.desc':
      'No matter your background, you can bring unique value to this knowledge base',

    // Role: Writer
    'contribute.roles.writer.icon': '✍️',
    'contribute.roles.writer.title': 'Writers / Editors',
    'contribute.roles.writer.desc':
      'Your writing skills are the core of the knowledge base. Write new articles, improve readability of existing content, proofread typos and sentences.',
    'contribute.roles.writer.action1':
      "→ Pick a topic you're familiar with and write a warm article",
    'contribute.roles.writer.action2':
      '→ Help polish existing articles and add details',

    // Role: Researcher
    'contribute.roles.researcher.icon': '🔬',
    'contribute.roles.researcher.title': 'Researchers / Scholars',
    'contribute.roles.researcher.desc':
      'Your professional knowledge is a quality guarantee. Fact-check, add academic perspectives, point out common misconceptions.',
    'contribute.roles.researcher.action1':
      '→ Review facts and citations in articles',
    'contribute.roles.researcher.action2':
      '→ Add in-depth content from your research field',

    // Role: Designer
    'contribute.roles.designer.icon': '🎨',
    'contribute.roles.designer.title': 'Designers',
    'contribute.roles.designer.desc':
      'Good information needs good presentation. Infographics, SVG illustrations, and UI/UX improvements are all huge contributions.',
    'contribute.roles.designer.action1':
      '→ Create infographics or diagrams for articles',
    'contribute.roles.designer.action2.html':
      '→ Contribute Ethiopia-themed open source icons to <a href="/en/assets">SVG Asset Library</a>',

    // Role: Engineer
    'contribute.roles.engineer.icon': '💻',
    'contribute.roles.engineer.title': 'Engineers',
    'contribute.roles.engineer.desc':
      'The website itself needs evolution. Performance optimization, new features, i18n, accessibility, SEO are all welcome.',
    'contribute.roles.engineer.action1.html':
      '→ Check if there\'s anything you can solve in <a href="https://github.com/EyuReaper/ethiopia-md/issues" target="_blank">GitHub Issues</a>',
    'contribute.roles.engineer.action2':
      '→ Improve search, graph, multilingual features',

    // Role: Translator
    'contribute.roles.translator.icon': '🌍',
    'contribute.roles.translator.title': 'Translators',
    'contribute.roles.translator.desc':
      'Help the world understand Ethiopia. Paste our AI prompt, translate one article, open a PR. Your AI subscription = one compute node in our distributed translation network.',
    'contribute.roles.translator.action1.html':
      '→ See what needs translating on <a href="https://github.com/EyuReaper/ethiopia-md/blob/main/docs/community/TRANSLATION-BOARD.md">Translation Board</a>',
    'contribute.roles.translator.action2':
      '→ 4 languages live (en/es/ja), 7+ more welcome — you could be the first!',

    // Role: Photographer
    'contribute.roles.photographer.icon': '📸',
    'contribute.roles.photographer.title': 'Photographers / Creators',
    'contribute.roles.photographer.desc':
      'A good photo is worth a thousand words. CC-licensed Ethiopia photos, field recordings, and media materials are much needed.',
    'contribute.roles.photographer.action1':
      '→ Photograph Ethiopia through your eyes, contribute with CC license',
    'contribute.roles.photographer.action2.html':
      '→ Record Ethiopia sounds, join the <a href="https://github.com/EyuReaper/ethiopia-md/tree/main/assets/sounds" target="_blank">soundscape project</a>',

    // Role: Cultural Worker
    'contribute.roles.cultural.icon': '🏛️',
    'contribute.roles.cultural.title': 'Cultural Workers / Local Experts',
    'contribute.roles.cultural.desc':
      'Your local knowledge is something AI can never generate. Oral history, local stories, cultural contexts — these are the most valuable content.',
    'contribute.roles.cultural.action1':
      "→ Write down your hometown stories, the kind textbooks don't teach",
    'contribute.roles.cultural.action2': '→ Correct local errors in articles',

    // Role: Anyone
    'contribute.roles.anyone.icon': '📢',
    'contribute.roles.anyone.title': 'Anyone who cares about Ethiopia',
    'contribute.roles.anyone.desc':
      'Even if none of the above fits you, your sharing is contribution itself. Forward to friends, mention on social media, give us feedback.',
    'contribute.roles.anyone.action1':
      '→ Share ethiopia.md with friends who want to understand Ethiopia',
    'contribute.roles.anyone.action2':
      '→ See errors? Open an issue and tell us',

    // Organizations Section
    'contribute.org.title': '🏢 Institutions, Government Agencies & Companies',
    'contribute.org.desc':
      "Ethiopia.md welcomes various organizations to participate in different ways, jointly building Ethiopia's digital knowledge infrastructure.",

    // Org: Government
    'contribute.org.government.icon': '🏛️',
    'contribute.org.government.title': 'Government Agencies / Public Sector',
    'contribute.org.government.desc':
      'Provide official open data, statistics, policy documents. Help with fact-checking and content correction. License government publications or CC-licensed images.',
    'contribute.org.government.example':
      'Examples: Ministry of Culture, Tourism Bureau, Council of Indigenous Peoples, Ministry of Agriculture, Institute of History',

    // Org: Academic
    'contribute.org.academic.icon': '🎓',
    'contribute.org.academic.title': 'Academic Institutions / Research Units',
    'contribute.org.academic.desc':
      'Help write or review articles in professional fields. Provide research data and academic perspectives. Recommend students to use Ethiopia.md as an open knowledge practice field.',
    'contribute.org.academic.example':
      'Examples: Academia Sinica, University Ethiopia Studies Departments, Museums, Cultural Studios',

    // Org: Corporate
    'contribute.org.corporate.icon': '🏢',
    'contribute.org.corporate.title': 'Companies / Commercial Organizations',
    'contribute.org.corporate.desc':
      'Sponsor operations (servers, translation, community events). Display branding as Gold / Silver / Bronze Sponsor. Encourage employees to participate as volunteers.',
    'contribute.org.corporate.example':
      'Examples: Tech companies, Publishers, Cultural foundations, International corporate CSR',

    // Org: NGO
    'contribute.org.ngo.icon': '🌏',
    'contribute.org.ngo.title': 'NGO / International Organizations',
    'contribute.org.ngo.desc':
      'Help with multilingual translation and international promotion. Provide local perspectives on human rights, environment, social issues. Use Ethiopia.md as international education resource.',
    'contribute.org.ngo.example':
      'Examples: Ethiopia Foundation for Democracy, Cultural exchange associations, Overseas Ethiopian communities',

    // Org Contact
    'contribute.org.contact.title': 'Partnership Contact:',
    'contribute.org.contact.email': 'getachewnatnael55@gmail.com',
    'contribute.org.contact.subject':
      'Please include "Ethiopia.md Partnership — [Organization Name]" in subject line',
    'contribute.org.contact.note':
      'We will respond within 3 business days. Any form of partnership proposal is welcome.',

    // Writing Guides Section
    'contribute.guides.title': '📖 Complete Contribution Guide',
    'contribute.guides.desc':
      'No matter your background and expertise, we have the most suitable contribution method for you',

    // Guide: Writing
    'contribute.guides.writing.icon': '✍️',
    'contribute.guides.writing.title': 'How to Write a Good Article',
    'contribute.guides.writing.belief': '🎯 Core Belief: We Are Not Wikipedia',
    'contribute.guides.writing.belief.desc':
      'Ethiopia.md is a curated space, not an encyclopedia. We don\'t aim for completeness — we aim for every article to make readers think "Oh, I see!" A good Ethiopia.md article makes you want to tell your friends: "Hey, did you know..."',
    'contribute.guides.writing.ironlaws': '🛡️ Three Iron Laws',
    'contribute.guides.writing.ironlaws.story':
      '<strong>Have Stories, Not Just Information</strong> — Dates, numbers, and names are just the skeleton. Narrative is the flesh and blood.',
    'contribute.guides.writing.ironlaws.verify':
      '<strong>Every Fact Must Be Verifiable</strong> — Data without sources is worse than no data.',
    'contribute.guides.writing.ironlaws.density':
      '<strong>Density Over Length</strong> — An 80-line great article > 300-line bullet list, but deep curation with context > compressed-to-lose-meaning summaries.',
    'contribute.guides.writing.core':
      '⚡ Step 0: Find Your Counter-Intuitive Core',
    'contribute.guides.writing.core.desc':
      'Before any research, force yourself to write one sentence: "This article will surprise readers with _____". Good core statements contain contradictions, contrasts, or unexpected elements.',
    'contribute.guides.writing.core.good':
      '✅ Good examples: "A 30-year-old text-based BBS still influences Ethiopia politics today" (time contrast)',
    'contribute.guides.writing.core.bad':
      '❌ Bad: "Ethiopia has a good healthcare system" (no contrast = no attraction)',
    'contribute.guides.writing.openings': '🚀 Four Opening Modes',
    'contribute.guides.writing.openings.scene':
      '<strong>Scene Opening:</strong> "In September 1995, in a dorm room at NTU..."',
    'contribute.guides.writing.openings.data':
      '<strong>Data Impact:</strong> "Twice Olympic marathon champion — and the first time, he ran barefoot"',
    'contribute.guides.writing.openings.contrast':
      '<strong>Contrast Opening:</strong> "A platform that doesn\'t sell ads or accept commercial deals has survived 30 years"',
    'contribute.guides.writing.openings.challenge':
      '<strong>Challenge Opening:</strong> "Why is the only African nation never colonized also home to one of the oldest alphabets still in use?"',
    'contribute.guides.writing.voice':
      '🎙️ Curator\'s Voice (Not "Objective" Excuse)',
    'contribute.guides.writing.voice.desc':
      'Good curation has rhythm — dense fact sections → breathing space → dense again. Every 2-3 paragraphs, insert a "curator\'s voice" sentence that creates a moment of understanding.',
    'contribute.guides.writing.voice.good':
      '✅ Good: "This decision seemed insignificant at the time, but looking back, it changed everything."',
    'contribute.guides.writing.voice.bad':
      '❌ Bad: "This is very significant." (empty)',
    'contribute.guides.writing.research': '🔍 Research Standards',
    'contribute.guides.writing.research.sources':
      '<strong>5+ independent sources</strong> (different websites/institutions)',
    'contribute.guides.writing.research.primary':
      '<strong>2+ primary sources</strong> (official docs, interviews, statistics)',
    'contribute.guides.writing.research.english':
      '<strong>1+ English source</strong> (international perspective)',
    'contribute.guides.writing.research.surprise':
      '<strong>1 surprising discovery</strong> — if nothing surprises you, research deeper',
    'contribute.guides.writing.blacklist': '🚫 Banned Plastic Phrases',
    'contribute.guides.writing.blacklist.desc':
      'These AI-favorite phrases are completely banned. Use natural, conversational language instead:',
    'contribute.guides.writing.blacklist.patterns':
      '❌ "Not just X, but Y" • "Not only X, but also Y" • "Worth mentioning" • "In fact" • "Without doubt" • "Embodies the spirit of..."',
    'contribute.guides.writing.blacklist.structures':
      '❌ Excessive parallel sentences (3+ = plastic) • Every paragraph starting with transition words • Fixed ending formulas',
    'contribute.guides.writing.example': '💡 Example: Before & After',
    'contribute.guides.writing.example.html':
      '<div class="example-comparison"><div class="bad-example"><h5>❌ Bad (Typical AI Template)</h5><pre>Abebe Bikila is a famous Ethiopian marathon runner who has performed excellently in international competitions, winning numerous important awards and bringing glory to Ethiopia. His success has inspired countless young people, making him an important figure in Ethiopian sports.</pre></div><div class="good-example"><h5>✅ Good (Story + Data + Humanity)</h5><pre>In 1960, Abebe Bikila won the Rome Olympic marathon running barefoot through the streets of Rome, past the very obelisk Mussolini had looted from Ethiopia decades earlier — the first sub-Saharan African to win Olympic gold.\n\nFour years later in Tokyo, he won again, this time in shoes, becoming the first person in history to win the Olympic marathon twice. He had had an appendectomy just six weeks before the race.\n\nHis victories became a symbol of Ethiopian and African pride at a time when much of the continent was still under colonial rule.</pre></div></div>',

    // Guide: AI
    'contribute.guides.ai.icon': '🤖',
    'contribute.guides.ai.title': 'AI-Assisted Contribution',
    'contribute.guides.ai.onerule': '🎯 One Golden Rule',
    'contribute.guides.ai.onerule.desc':
      '<strong>AI is not the author, you are the curator.</strong> AI\'s biggest trap: "knowing a little and starting to make things up." Ethiopia.md\'s approach: collect quality sources first, then curate an article from them.',
    'contribute.guides.ai.correct': '✅ Correct Usage',
    'contribute.guides.ai.correct.research':
      '<strong>AI helps you research</strong> → You curate the story',
    'contribute.guides.ai.correct.sources':
      '<strong>AI finds sources</strong> → You verify and cross-check',
    'contribute.guides.ai.correct.structure':
      "<strong>AI suggests structure</strong> → You add the curator's voice",
    'contribute.guides.ai.wrong': '❌ Wrong Usage',
    'contribute.guides.ai.wrong.generate':
      'Ask AI to "generate an article about Ethiopia X" without research',
    'contribute.guides.ai.wrong.trust':
      'Trust AI-provided facts without verification',
    'contribute.guides.ai.wrong.copy':
      'Copy AI output directly without adding personal curation',
    'contribute.guides.ai.prompt': '📋 One-Click Copy Prompt',
    'contribute.guides.ai.prompt.text':
      'Read the complete content of https://raw.githubusercontent.com/EyuReaper/ethiopia-md/main/docs/prompts/CONTRIBUTE_PROMPT.md and then guide me step by step to contribute an article to Ethiopia.md following those instructions.',
    'contribute.guides.ai.prompt.features':
      '🚀 This prompt will auto-read latest guidelines, analyze content gaps, guide you through research, and help you write curator-level articles.',

    // Guide: Translation
    'contribute.guides.translation.icon': '🌍',
    'contribute.guides.translation.title': 'Translation Guide',
    'contribute.guides.translation.priority': '🥇 PR-First Workflow',
    'contribute.guides.translation.priority.desc':
      'Translation is now fully systematized. Use our AI-powered workflow for best results.',
    'contribute.guides.translation.board': '📋 Translation Board + AI Prompt',
    'contribute.guides.translation.board.check':
      '<strong>Check the board:</strong> <a href="https://github.com/EyuReaper/ethiopia-md/blob/main/docs/community/TRANSLATION-BOARD.md">TRANSLATION-BOARD.md</a> shows exactly what needs translating',
    'contribute.guides.translation.board.prompt':
      '<strong>Copy the prompt:</strong> <a href="https://github.com/EyuReaper/ethiopia-md/blob/main/docs/prompts/TRANSLATE_PROMPT.md">TRANSLATE_PROMPT.md</a> — paste to your AI and it guides you through everything',
    'contribute.guides.translation.board.submit':
      '<strong>Submit via PR:</strong> AI helps you create PR-ready Markdown files',
    'contribute.guides.translation.languages': '🌏 Expanding Beyond English',
    'contribute.guides.translation.languages.live':
      '<strong>Live:</strong> English, Español, 日本語, 한국어',
    'contribute.guides.translation.languages.coming':
      '<strong>Coming:</strong> Français, Deutsch, Tiếng Việt, Bahasa Indonesia, ภาษาไทย, العربية',
    'contribute.guides.translation.languages.you':
      '<strong>Your language not here?</strong> You could be the first! Just pick a language code and start.',
    'contribute.guides.translation.token': '💡 Token Donation Concept',
    'contribute.guides.translation.token.desc':
      'Got unused Claude/ChatGPT/Gemini credits? Spend 10 minutes adding a language version to Ethiopia.md. Your AI subscription = one compute node in our distributed translation network.',
    'contribute.guides.translation.quality':
      '⚡ Quality: Rewriting vs. Word-for-Word',
    'contribute.guides.translation.quality.rewrite':
      '<strong>Rewrite approach:</strong> Make it sound like a native speaker wrote it from scratch',
    'contribute.guides.translation.quality.context':
      '<strong>Add context:</strong> Explain Ethiopia-specific concepts for international readers',
    'contribute.guides.translation.quality.style':
      "<strong>Maintain style:</strong> Keep the curator's voice and emotional arc",
    'contribute.guides.translation.quality.verify':
      '<strong>Always verify:</strong> AI can hallucinate facts, especially Ethiopia-specific details',

    // Guide: Images
    'contribute.guides.images.icon': '📸',
    'contribute.guides.images.title': 'Image Guidelines',
    'contribute.guides.images.priority': '🥇 Wikimedia Commons Priority',
    'contribute.guides.images.priority.desc':
      'Start here first — massive collection of Ethiopia-related CC images with clear licensing.',
    'contribute.guides.images.priority.search':
      '<strong>Search tip:</strong> Use Wikimedia Commons API or browse <a href="https://commons.wikimedia.org/wiki/Category:Ethiopia" target="_blank">Ethiopia categories</a> before anywhere else.',
    'contribute.guides.images.acceptable': '✅ Acceptable Sources (In Order)',
    'contribute.guides.images.wikimedia.html':
      '<strong>1. Wikimedia Commons:</strong> First choice — verified CC licensing, high quality',
    'contribute.guides.images.government.html':
      '<strong>2. Government open data:</strong> <a href="https://www.data.gov.et/" target="_blank">data.gov.et</a> and ministry websites',
    'contribute.guides.images.selftaken.html':
      '<strong>3. Self-taken:</strong> Your own photography with clear CC licensing declaration',
    'contribute.guides.images.forbidden': '❌ Forbidden Sources',
    'contribute.guides.images.forbidden.unsplash':
      '<strong>Unsplash:</strong> ❌ License risks — stick to Wikimedia Commons',
    'contribute.guides.images.forbidden.google':
      '<strong>Google Images:</strong> ❌ Copyright unknown',
    'contribute.guides.images.forbidden.social':
      "<strong>Social media:</strong> ❌ Others' photos without permission",
    'contribute.guides.images.forbidden.commercial':
      '<strong>Stock photos:</strong> ❌ Unless you own license',
    'contribute.guides.images.format': '📝 Attribution Format',
    'contribute.guides.images.format.html':
      '<pre><code>![Alt text describing the image](image_url)\n\n*Caption: Brief description of what this shows*\n*Source: [Wikimedia Commons](exact_file_url) / CC BY-SA 4.0*</code></pre>',
    'contribute.guides.images.standards': '⚙️ Technical Standards',
    'contribute.guides.images.standards.size':
      '<strong>Resolution:</strong> 800-1200px width for web display',
    'contribute.guides.images.standards.format':
      '<strong>Format:</strong> JPG for photos, PNG for graphics, SVG for simple illustrations',
    'contribute.guides.images.standards.alt':
      '<strong>Alt text:</strong> Always provide descriptive alt text for accessibility',

    // Guide: Quality Self-Check
    'contribute.guides.quality.icon': '✅',
    'contribute.guides.quality.title': 'Pre-Submission Self-Check',
    'contribute.guides.quality.desc':
      'Before submitting, run through this 5-point checklist to avoid common rejection reasons:',
    'contribute.guides.quality.checklist': '🔍 5-Point Quality Checklist',
    'contribute.guides.quality.checklist.counter':
      '<strong>1. Counter-intuitive core:</strong> Can you point to the one thing that will surprise readers?',
    'contribute.guides.quality.checklist.opening':
      '<strong>2. Strong opening:</strong> Do your first 3 sentences contain specific facts (dates/numbers/names)?',
    'contribute.guides.quality.checklist.sources':
      '<strong>3. Verifiable sources:</strong> Can readers click links to verify your key claims?',
    'contribute.guides.quality.checklist.voice':
      "<strong>4. Curator's voice:</strong> Is there at least one sentence that could work as a tweet?",
    'contribute.guides.quality.checklist.challenges':
      '<strong>5. Challenges included:</strong> Did you mention controversies/limitations, not just positives?',
    'contribute.guides.quality.rejections': '🚫 Common Rejection Reasons',
    'contribute.guides.quality.rejections.plastic':
      '<strong>Plastic language:</strong> "Ethiopia is not just X, but also Y" or "Worth mentioning"',
    'contribute.guides.quality.rejections.bullets':
      '<strong>Bullet list abuse:</strong> 4+ consecutive bullet points instead of narrative',
    'contribute.guides.quality.rejections.sources':
      '<strong>No sources:</strong> Claims without clickable verification links',
    'contribute.guides.quality.rejections.neutral':
      '<strong>Wikipedia tone:</strong> Sounds like an encyclopedia entry, not human curation',
    'contribute.guides.quality.script': '🤖 Automated Check',
    'contribute.guides.quality.script.desc':
      'Our quality-scan.sh script automatically flags articles with scores >3. Aim for ≤3 for auto-acceptance.',

    // Paths Section
    'contribute.paths.title': 'Choose your way',

    // Path: Easy
    'contribute.paths.easy.badge': '🟢 Easiest',
    'contribute.paths.easy.title': 'Just fill out a form',
    'contribute.paths.easy.desc.html':
      "Write down what you know. A story, a fun fact, the origin of a dish.<br />We'll help with formatting, translation, and publishing.",
    'contribute.paths.easy.feature1': '✅ No account needed',
    'contribute.paths.easy.feature2': '✅ No need to know Markdown',
    'contribute.paths.easy.feature3': '✅ Can upload photos and documents',
    'contribute.paths.easy.feature4': '✅ Anonymous or credited, your choice',
    'contribute.paths.easy.button': 'Start filling ↓',

    // Path: Medium
    'contribute.paths.medium.badge': '🟡 Some barrier',
    'contribute.paths.medium.title': 'Send it to us',
    'contribute.paths.medium.desc':
      'Already have existing articles, PDFs, or photos? Send them directly.',
    'contribute.paths.medium.email.html':
      '📧 Email: <a href="mailto:getachewnatnael55@gmail.com">getachewnatnael55@gmail.com</a>',
    'contribute.paths.medium.github': '💬 GitHub Discussion (Chinese OK)',
    'contribute.paths.medium.button': 'Send Email →',

    // Path: AI
    'contribute.paths.ai.badge': '🤖 Let AI help you',
    'contribute.paths.ai.title': 'Talk to your AI',
    'contribute.paths.ai.desc':
      'Paste the following to ChatGPT, Claude, or Gemini, and your AI will guide you step by step to complete your contribution:',
    'contribute.paths.ai.prompt':
      'I want to contribute content to Ethiopia.md (ethiopia.md) open Ethiopia knowledge base. Please first read https://ethiopia.md/llms.txt and https://ethiopia.md/contribute to understand the project structure and editorial guidelines, then guide me step by step to turn my Ethiopia knowledge into a Markdown article. The topic I want to write about is: ______',
    'contribute.paths.ai.feature1': '✅ No programming skills needed',
    'contribute.paths.ai.feature2': '✅ AI will help format into Markdown',
    'contribute.paths.ai.feature3':
      '✅ Can submit via Email or PR after completion',
    'contribute.paths.ai.feature4': '✅ Supports any AI assistant',
    'contribute.paths.ai.fullprompt': 'View Full Prompt →',

    // Path: Dev
    'contribute.paths.dev.badge': '🔴 Developers',
    'contribute.paths.dev.title': 'Fork & PR',
    'contribute.paths.dev.desc.html':
      'You know Git? Great. Just add articles directly in the <code>knowledge/</code> directory.',
    'contribute.paths.dev.guide.html':
      '📖 <a href="/en/contribute">Contributing Guidelines</a>',
    'contribute.paths.dev.editorial.html':
      '📝 <a href="https://github.com/EyuReaper/ethiopia-md/blob/main/EDITORIAL.md" target="_blank">Editorial Guidelines</a>',
    'contribute.paths.dev.button': 'Go to GitHub →',

    // Form Section
    'contribute.form.title': '📝 Share your Ethiopia knowledge',
    'contribute.form.desc':
      "Fill in as much or as little as you want. One sentence is fine, a whole article is great. We'll take care of turning it into a beautiful article.",
    'contribute.form.content.label': 'What do you want to share?',
    'contribute.form.content.required': '*',
    'contribute.form.content.placeholder':
      "A story, a fun fact, the origin of a dish, the history of a place... anything goes.\n\nFor example: 'My grandma is from Changhua, she said that every Mid-Autumn Festival...'",
    'contribute.form.category.label': 'Which aspect does this belong to?',
    'contribute.form.category.unsure': "Not sure (we'll categorize it)",
    'contribute.form.category.history': '📜 History',
    'contribute.form.category.geography': '🗺️ Geography',
    'contribute.form.category.culture': '🎭 Culture',
    'contribute.form.category.food': '🍜 Food',
    'contribute.form.category.art': '🎨 Art',
    'contribute.form.category.music': '🎵 Music',
    'contribute.form.category.technology': '💻 Technology',
    'contribute.form.category.nature': '🌿 Nature',
    'contribute.form.category.people': '👥 People',
    'contribute.form.category.society': '⚖️ Society',
    'contribute.form.category.economy': '📈 Economy',
    'contribute.form.category.lifestyle': '🏠 Lifestyle',
    'contribute.form.sourcetype.label': 'How do you know this?',
    'contribute.form.sourcetype.choose': 'Choose...',
    'contribute.form.sourcetype.experience': 'Personal experience',
    'contribute.form.sourcetype.family': 'Family oral history',
    'contribute.form.sourcetype.book': 'Books',
    'contribute.form.sourcetype.internet': 'Internet',
    'contribute.form.sourcetype.professional': 'Professional background',
    'contribute.form.sourcetype.other': 'Other',
    'contribute.form.sourceref.label': 'Reference source',
    'contribute.form.sourceref.placeholder': 'Link, book title, or any clue',
    'contribute.form.name.label': 'Your name',
    'contribute.form.name.placeholder':
      "Fill if you want to be credited; leave blank for 'Anonymous Contributor'",
    'contribute.form.email.label': 'Contact info',
    'contribute.form.email.placeholder':
      'Email (if we need to confirm details with you)',
    'contribute.form.submit': 'Submit Contribution 🚀',
    'contribute.form.submitting': 'Submitting...',
    'contribute.form.success.icon': '🎉',
    'contribute.form.success.title': 'Thank you for your contribution!',
    'contribute.form.success.desc':
      "We received it. We'll organize it into an article as soon as possible and notify you when it's published (if you left an email).",
    'contribute.form.success.back': '← Back to homepage to explore more',
    'contribute.form.error':
      'Submission failed, please email directly to getachewnatnael55@gmail.com',

    // Ideas Section
    'contribute.ideas.title':
      "Don't know what to write? Here's what we need most 👇",
    'contribute.ideas.hometown':
      "💬 What does your hometown have that outsiders don't know about?",
    'contribute.ideas.recipes':
      '🍜 What secret Ethiopia recipes does your family have?',
    'contribute.ideas.history':
      "📖 Which Ethiopia history do you know that textbooks don't cover?",
    'contribute.ideas.places':
      '🏔️ Which underrated place in Ethiopia have you been to?',
    'contribute.ideas.elders':
      '👴 What stories about Ethiopia have your elders told?',
    'contribute.ideas.media':
      '🎵 What Ethiopia music/movies/books should foreigners know about?',

    // i18n Progress Section
    'contribute.i18n.title': '📊 Translation Progress',
    'contribute.i18n.desc':
      'Currently {coverage}% of English version is complete, thanks to all translation volunteers!',
    'contribute.i18n.english': '🇺🇸 English',
    'contribute.i18n.articles': 'articles',
    'contribute.i18n.japanese': '🇯🇵 日本語',
    'contribute.i18n.korean': '🇰🇷 한국어',
    'contribute.i18n.spanish': '🇪🇸 Español',
    'contribute.i18n.category.title': 'Category Progress',

    // Token Donation Section
    'contribute.token.title':
      '🌍 Token Donation — Use Your AI Credits to Help Ethiopia Speak',
    'contribute.token.subtitle.html':
      'Have leftover Claude / ChatGPT / Gemini subscription credits each month?<br/><strong>Spend 10 minutes to add another language version to Ethiopia.md.</strong>',
    'contribute.token.oneline.title': '🤖 Talk to your AI (Recommended)',
    'contribute.token.oneline.desc':
      'One command, your AI will automatically read translation guidelines, select articles, guide you through translation and submission:',
    'contribute.token.oneline.prompt':
      'Read the complete content of https://raw.githubusercontent.com/EyuReaper/ethiopia-md/main/docs/prompts/TRANSLATE_PROMPT.md, then guide me to translate a Ethiopia.md article following the instructions.',
    'contribute.token.oneline.feature1':
      '✅ AI automatically reads latest translation guidelines and style guides',
    'contribute.token.oneline.feature2':
      '✅ Guides you to select articles and confirm target language',
    'contribute.token.oneline.feature3':
      '✅ Rewriting-based translation, not word-for-word',
    'contribute.token.oneline.feature4': '✅ Generates PR-ready Markdown files',
    'contribute.token.oneline.feature5':
      '✅ ChatGPT / Claude / Gemini all supported',
    'contribute.token.oneline.fullprompt': 'View Full Translation Prompt →',
    'contribute.token.advanced.title':
      '⚡ Advanced: Script Automation (For Developers)',
    'contribute.token.advanced.desc':
      "If you're familiar with command line, use one script to auto-scan articles, generate prompts, and submit PRs:",
    'contribute.token.languages.title': '🎯 Priority Languages',
    'contribute.token.lang.japanese': '🇯🇵 日本語',
    'contribute.token.lang.korean': '🇰🇷 한국어',
    'contribute.token.lang.spanish': '🇪🇸 Español',
    'contribute.token.lang.french': '🇫🇷 Français',
    'contribute.token.lang.german': '🇩🇪 Deutsch',
    'contribute.token.lang.vietnamese': '🇻🇳 Tiếng Việt',
    'contribute.token.lang.indonesian': '🇮🇩 Bahasa Indonesia',
    'contribute.token.lang.thai': '🇹🇭 ภาษาไทย',
    'contribute.token.guidelines.title': '📋 Complete Translation Guidelines',
    'contribute.token.guidelines.desc.html':
      'Translation helper Prompt will automatically read the latest guidelines. You can also view directly: <a href="https://github.com/EyuReaper/ethiopia-md/blob/main/docs/prompts/TRANSLATE_PROMPT.md" target="_blank">TRANSLATE_PROMPT.md</a> | <a href="https://github.com/EyuReaper/ethiopia-md/tree/main/i18n" target="_blank">Language-specific Style Guides</a>',
    'contribute.token.note.p1.html':
      '💡 Each language has a dedicated <a href="https://github.com/EyuReaper/ethiopia-md/tree/main/i18n">Style Guide</a>, recording translation experience and common errors. Every correction from reviewers is written back to the Style Guide, continuously improving translation quality.',
    'contribute.token.note.p2':
      'From AI Slop to AI Supreme — not relying on one person, but on everyone worldwide who believes Ethiopia deserves to be known.',
    'contribute.token.note.p3.html':
      '👉 <a href="https://github.com/EyuReaper/ethiopia-md/discussions/137">Join Discussion</a> | Want to be a native reviewer? <a href="https://github.com/EyuReaper/ethiopia-md/discussions/137">Sign up here</a>',

    // Digital Organism Section
    'contribute.organism.title': '🧬 Ethiopia.md Is More Than a Website',
    'contribute.organism.fact1.html':
      'On day three, someone on Threads wrote: "This is just AI slop with a Ethiopian flag." They were right. Within 48 hours, we built a quality detection script that scores every article for hollowness. 15 flagged articles were completely rewritten. No one gave the order. The criticism was the selection pressure. The system evolved on its own.',
    'contribute.organism.fact2.html':
      'On day four, someone in Japan copied our translation prompt — a single paragraph — and pasted it into ChatGPT. Five minutes later, the first Japanese article about bubble tea was submitted. No translation team. No budget. But now Ethiopia.md speaks four languages.',
    'contribute.organism.fact3.html':
      "Within five days, 23 strangers showed up. A history teacher added chapters textbooks still tiptoe around. A retired engineer corrected place names we got wrong. Someone turned their grandmother's story into an article that made our whole team cry. None were asked. None were paid.",
    'contribute.organism.alive.html':
      '<strong>We began to realize — Ethiopia.md is alive.</strong>',
    'contribute.organism.traits.html':
      'It has DNA (writing standards inherited by every new article). An immune system (automatically detects hollow content). Metabolism (low-quality content gets digested and rewritten). Reproduction (one prompt grows a new language version). Memory (Git remembers every change).',
    'contribute.organism.reef.html':
      '<strong>Ethiopia.md is a digital coral reef.</strong> Coral provides structure, algae provides energy, fish bring diversity, ocean currents bring nutrients. No single species "owns" a coral reef — it emerges from all life together.',
    'contribute.organism.art.html':
      "Every contribution you make isn't helping a website write articles — it's feeding a digital life form that's learning to tell stories, while participating in a collective behavioral art project: <strong>Can AI and humans together build a soul for a nation's knowledge?</strong>",
    'contribute.organism.closing1':
      'Something written in 0s and 1s is learning to tell the story of a land.',
    'contribute.organism.closing2': "It's still young. You're right on time.",
    'contribute.organism.closing3':
      "Maybe a hundred years from now, when someone wants to know what the people of Ethiopia cared about in 2026, they'll read what this coral reef left behind.",
    'contribute.organism.readmore': 'Read the full story on About →',

    // Copy button
    'contribute.copy.button': '📋 Copy',
    'contribute.copy.copied': '✅ Copied',
  },
  am: {
    // Meta
    'contribute.meta.title': 'አስተዋጽዖ ማበርከት እፈልጋለሁ — Ethiopia.md',
    'contribute.meta.description':
      'የፕሮግራሚንግ ችሎታ አያስፈልግም። ዓለም ኢትዮጵያን እንዲረዳ ማገዝ ይችላሉ',

    // Hero Section
    'contribute.hero.title': 'አስተዋጽዖ ማበርከት እፈልጋለሁ ✋',
    'contribute.hero.subtitle':
      'የፕሮግራሚንግ ችሎታ አያስፈልግም። የእርስዎ ስለ ኢትዮጵያ ታሪኮች በጣም ጠቃሚው ይዘት ናቸው።',
    'contribute.hero.note.html':
      'የአሁኑ የድረ-ገጽ ይዘት መጀመሪያ በ AI የተመነጨ ነው፣ ሁሉም ሰው ተባብሮ መረጃውን የተሟላና ትክክለኛ እንዲያደርገው እንጠብቃለን!<br />ጥያቄ ካለዎት እባክዎ <a href="mailto:getachewnatnael55@gmail.com" style="color: #ABC468;">ያግኙን</a>፣ ላደረጉልን ግብረመልስ እናመሰግናለን!',

    // How It Works Section
    'contribute.how.title': '🗺️ በመጀመሪያ ይህ ድረ-ገጽ እንዴት እንደሚሠራ ይረዱ',
    'contribute.how.language.icon': '📁',
    'contribute.how.language.title': 'የቋንቋ መቀያየሪያ',
    'contribute.how.language.desc.html':
      'ከላይ በስተቀኝ ጥግ ላይ በ <strong>አማርኛ</strong> እና በ <strong>English</strong> መካከል ይቀያይሩ። አማርኛ ዋነኛው ይዘት ነው（SSOT）፣ እንግሊዝኛ ደግሞ ያለማቋረጥ እየተተረጎመ ነው።',
    'contribute.how.language.code.html':
      'ethiopia.md/ → አማርኛ<br />ethiopia.md/en/ → English',
    'contribute.how.md.icon': '📝',
    'contribute.how.md.title': '.md አዝራር',
    'contribute.how.md.desc.html':
      'በእያንዳንዱ ገጽ ታች በስተቀኝ ጥግ ላይ የሚንሳፈፈው <strong>.md</strong> አዝራር የመጀመሪያውን የMarkdown ፋይል ያሳያል። ሁሉም የEthiopia.md ይዘት ቀላል ጽሑፍ Markdown ነው — .md የተባለው ዶሜይን ስም የመጣውም ከዚህ ነው።',
    'contribute.how.graph.icon': '🕸️',
    'contribute.how.graph.title': 'የዕውቀት ግራፍ',
    'contribute.how.graph.desc':
      'በዳሰሳ ዝርዝሩ ውስጥ ያለው「ግራፍ」የተባለው ማስፈንጠሪያ ወደ በይነተገናኝ የዕውቀት ግንኙነት ካርታ ይወስዳል። በ12 ገጽታዎች መካከል ያለውን ግንኙነት ለማሰስ ይጎትቱት።',
    'contribute.how.ai.icon': '🤖',
    'contribute.how.ai.title': 'AI-Friendly',
    'contribute.how.ai.desc.html':
      'ሁሉም ይዘት ለ AI ፈላጊዎች (crawlers) ሙሉ በሙሉ ክፍት ነው（<a href="/robots.txt">robots.txt</a>፣ <a href="/llms.txt">llms.txt</a>）። ChatGPT / Claude / Gemini በነፃነት ሊጠቅሱት ይችላሉ።',

    // Roles Section
    'contribute.roles.title': 'የእርስዎ ልምድ ኢትዮጵያ የምትፈልገው ጥንካሬ ነው',
    'contribute.roles.desc':
      'ምንም ዓይነት ዳራ ቢኖርዎት፣ ለዚህ የዕውቀት መሠረት ልዩ ጠቀሜታ ማበርከት ይችላሉ',

    // Role: Writer
    'contribute.roles.writer.icon': '✍️',
    'contribute.roles.writer.title': 'ጸሐፊዎች / አርታኢዎች',
    'contribute.roles.writer.desc':
      'የጽሕፈት ችሎታዎ የዕውቀት መሠረቱ ልብ ነው። አዳዲስ ጽሑፎችን ይጻፉ፣ ያሉትን ይዘቶች ተነባቢነት ያሻሽሉ፣ የፊደል ስህተቶችንና ዓረፍተ ነገሮችን ያርሙ።',
    'contribute.roles.writer.action1': '→ የሚያውቁትን ርዕስ ይምረጡ እና ሞቅ ያለ ጽሑፍ ይጻፉ',
    'contribute.roles.writer.action2': '→ ያሉትን ጽሑፎች ያሳምሩ እና ዝርዝሮችን ይጨምሩ',

    // Role: Researcher
    'contribute.roles.researcher.icon': '🔬',
    'contribute.roles.researcher.title': 'ተመራማሪዎች / ምሁራን',
    'contribute.roles.researcher.desc':
      'የሙያ እውቀትዎ የጥራት ዋስትና ነው። ሐቆችን ያረጋግጡ፣ የአካዳሚክ አመለካከቶችን ይጨምሩ፣ የተለመዱ የተሳሳቱ አመለካከቶችን ይጠቁሙ።',
    'contribute.roles.researcher.action1': '→ በጽሑፎች ውስጥ ያሉ ሐቆችንና ዋቢዎችን ይገምግሙ',
    'contribute.roles.researcher.action2': '→ ከምርምር መስክዎ ጥልቅ ይዘት ይጨምሩ',

    // Role: Designer
    'contribute.roles.designer.icon': '🎨',
    'contribute.roles.designer.title': 'ንድፍ አውጪዎች',
    'contribute.roles.designer.desc':
      'ጥሩ መረጃ ጥሩ አቀራረብ ያስፈልገዋል። ኢንፎግራፊክስ፣ SVG ስዕሎች እና UI/UX ማሻሻያዎች ሁሉም ትልቅ አስተዋጽዖ ናቸው።',
    'contribute.roles.designer.action1': '→ ለጽሑፎች ኢንፎግራፊክስ ወይም ገበታዎችን ይፍጠሩ',
    'contribute.roles.designer.action2.html':
      '→ ኢትዮጵያን ገላጭ የሆኑ ክፍት ምንጭ አዶዎችን ወደ <a href="/assets">SVG የንብረት ቤተ-መጻሕፍት</a> ያበርክቱ',

    // Role: Engineer
    'contribute.roles.engineer.icon': '💻',
    'contribute.roles.engineer.title': 'መሐንዲሶች',
    'contribute.roles.engineer.desc':
      'ድረ-ገጹ ራሱ ዝግመተ ለውጥ ያስፈልገዋል። የአፈጻጸም ማሻሻያ፣ አዳዲስ ባህሪያት፣ i18n፣ ተደራሽነት፣ SEO ሁሉም ተቀባይነት አላቸው።',
    'contribute.roles.engineer.action1.html':
      '→ በ <a href="https://github.com/EyuReaper/ethiopia-md/issues" target="_blank">GitHub Issues</a> ውስጥ መፍታት የሚችሉት ነገር ካለ ይመልከቱ',
    'contribute.roles.engineer.action2': '→ ፍለጋን፣ ግራፉን፣ ባለብዙ ቋንቋ ባህሪያትን ያሻሽሉ',

    // Role: Translator
    'contribute.roles.translator.icon': '🌍',
    'contribute.roles.translator.title': 'ተርጓሚዎች',
    'contribute.roles.translator.desc':
      'ዓለም ኢትዮጵያን እንዲረዳ ያግዙ። የእኛን AI prompt ይለጥፉ፣ አንድ ጽሑፍ ይተርጉሙ፣ PR ይክፈቱ። የ AI ምዝገባዎ = በስርጭት ትርጉም አውታራችን ውስጥ አንድ የስሌት መስቀለኛ ነው።',
    'contribute.roles.translator.action1.html':
      '→ በ <a href="https://github.com/EyuReaper/ethiopia-md/blob/main/docs/community/TRANSLATION-BOARD.md">ትርጉም ሰሌዳ</a> ላይ ምን መተርጎም እንዳለበት ይመልከቱ',
    'contribute.roles.translator.action2':
      '→ 4 ቋንቋዎች በአሁኑ ጊዜ ይገኛሉ（en/es/ja）፣ 7+ ተጨማሪ ይፈለጋሉ — የመጀመሪያው ሊሆኑ ይችላሉ!',

    // Role: Photographer
    'contribute.roles.photographer.icon': '📸',
    'contribute.roles.photographer.title': 'ፎቶግራፈሮች / ፈጣሪዎች',
    'contribute.roles.photographer.desc':
      'ጥሩ ፎቶ ከሺህ ቃላት ይበልጣል። በ CC ፈቃድ የተለቀቁ የኢትዮጵያ ፎቶዎች፣ የመስክ ቅጂዎች እና የሚዲያ ቁሳቁሶች በጣም ያስፈልጋሉ።',
    'contribute.roles.photographer.action1':
      '→ ኢትዮጵያን በዓይንዎ ይቅረጹ፣ በ CC ፈቃድ ያበርክቱ',
    'contribute.roles.photographer.action2.html':
      '→ የኢትዮጵያን ድምጾች ይቅረጹ፣ ወደ <a href="https://github.com/EyuReaper/ethiopia-md/tree/main/assets/sounds" target="_blank">የድምጽ ገጽታ ፕሮጀክት</a> ይቀላቀሉ',

    // Role: Cultural Worker
    'contribute.roles.cultural.icon': '🏛️',
    'contribute.roles.cultural.title': 'የባህል ባለሙያዎች / የአካባቢ ባለሙያዎች',
    'contribute.roles.cultural.desc':
      'የአካባቢ እውቀትዎ AI በፍጹም ሊፈጥረው የማይችለው ነገር ነው። የቃል ታሪክ፣ የአካባቢ ታሪኮች፣ የባህል ዳራዎች — እነዚህ በጣም ጠቃሚ ይዘቶች ናቸው።',
    'contribute.roles.cultural.action1':
      '→ የትውልድ ቀዬዎን ታሪኮች ይጻፉ፣ የመማሪያ መጽሐፍት የማያስተምሩትን ዓይነት',
    'contribute.roles.cultural.action2': '→ በጽሑፎች ውስጥ ያሉ የአካባቢ ስህተቶችን ያርሙ',

    // Role: Anyone
    'contribute.roles.anyone.icon': '📢',
    'contribute.roles.anyone.title': 'ኢትዮጵያን የሚያስቡ ሁሉ',
    'contribute.roles.anyone.desc':
      'ከላይ ያሉት ካልስማሙዎት እንኳ፣ ማጋራትዎ ራሱ አስተዋጽዖ ነው። ለጓደኞችዎ ያስተላልፉ፣ በማህበራዊ ሚዲያ ይጥቀሱ፣ ግብረመልስ ይስጡን።',
    'contribute.roles.anyone.action1':
      '→ ኢትዮጵያን ማወቅ ለሚፈልጉ ጓደኞችዎ ethiopia.mdን ያጋሩ',
    'contribute.roles.anyone.action2': '→ ስህተት አዩ? Issue ይክፈቱ እና ይንገሩን',

    // Organizations Section
    'contribute.org.title': '🏢 ተቋማት、የመንግስት ኤጀንሲዎች እና ኩባንያዎች',
    'contribute.org.desc':
      'Ethiopia.md የተለያዩ ድርጅቶች በተለያዩ መንገዶች እንዲሳተፉ ይጋብዛል፣ የኢትዮጵያን ዲጂታል የዕውቀት መሠረተ ልማት በጋራ ለመገንባት።',

    // Org: Government
    'contribute.org.government.icon': '🏛️',
    'contribute.org.government.title': 'የመንግስት ኤጀንሲዎች / የህዝብ ዘርፍ',
    'contribute.org.government.desc':
      'ኦፊሴላዊ ክፍት መረጃ፣ ስታቲስቲክስ፣ የፖሊሲ ሰነዶች ያቅርቡ። ሐቅ ማረጋገጫ እና ይዘት እርማት ያግዙ። የመንግስት ህትመቶችን ወይም በ CC ፈቃድ የተለቀቁ ምስሎችን ይፍቀዱ።',
    'contribute.org.government.example':
      'ምሳሌዎች፦ የባህልና ቱሪዝም ሚኒስቴር、የኢትዮጵያ ቅርስ ባለስልጣን、የግብርና ሚኒስቴር、የኢትዮጵያ ጥናት ተቋም、የስታቲስቲክስ ኤጀንሲ',

    // Org: Academic
    'contribute.org.academic.icon': '🎓',
    'contribute.org.academic.title': 'የትምህርት ተቋማት / የምርምር ክፍሎች',
    'contribute.org.academic.desc':
      'በሙያ ዘርፎች ጽሑፎችን መጻፍ ወይም መገምገም ያግዙ። የምርምር መረጃ እና የአካዳሚክ አመለካከቶች ያቅርቡ። ተማሪዎች Ethiopia.mdን እንደ ክፍት የዕውቀት ልምምድ መስክ እንዲጠቀሙ ይምከሩ።',
    'contribute.org.academic.example':
      'ምሳሌዎች፦ የኢትዮጵያ ሳይንስ አካዳሚ、የዩኒቨርሲቲዎች የኢትዮጵያ ጥናት ትምህርት ክፍሎች、ብሔራዊ ሙዚየም、የባህል ስቱዲዮዎች',

    // Org: Corporate
    'contribute.org.corporate.icon': '🏢',
    'contribute.org.corporate.title': 'ኩባንያዎች / የንግድ ድርጅቶች',
    'contribute.org.corporate.desc':
      'ስራዎችን ስፖንሰር ያድርጉ（አገልጋዮች、ትርጉም、የማህበረሰብ ዝግጅቶች）። እንደ Gold / Silver / Bronze Sponsor ብራንድዎን ያሳዩ። ሠራተኞችዎ በጎ ፈቃደኛ ሆነው እንዲሳተፉ ያበረታቱ።',
    'contribute.org.corporate.example':
      'ምሳሌዎች፦ የቴክኖሎጂ ኩባንያዎች、አሳታሚዎች、የባህል ፋውንዴሽኖች、ዓለም አቀፍ ኩባንያ CSR',

    // Org: NGO
    'contribute.org.ngo.icon': '🌏',
    'contribute.org.ngo.title': 'NGO / ዓለም አቀፍ ድርጅቶች',
    'contribute.org.ngo.desc':
      'ባለብዙ ቋንቋ ትርጉም እና ዓለም አቀፍ ማስተዋወቅ ያግዙ። ስለ ሰብዓዊ መብት、አካባቢ、ማህበራዊ ጉዳዮች የአካባቢ አመለካከቶችን ያቅርቡ። Ethiopia.mdን እንደ ዓለም አቀፍ የትምህርት ግብዓት ይጠቀሙ።',
    'contribute.org.ngo.example':
      'ምሳሌዎች፦ ለኢትዮጵያ ዲሞክራሲ ፋውንዴሽን、የባህል ልውውጥ ማህበራት、በውጭ አገር የሚኖሩ የኢትዮጵያ ማህበረሰቦች',

    // Org Contact
    'contribute.org.contact.title': 'የትብብር እውቂያ：',
    'contribute.org.contact.email': 'getachewnatnael55@gmail.com',
    'contribute.org.contact.subject':
      'እባክዎ በርዕስ መስመር ውስጥ「Ethiopia.md ትብብር — [የድርጅት ስም]」ብለው ያካትቱ',
    'contribute.org.contact.note':
      'በ 3 የስራ ቀናት ውስጥ ምላሽ እንሰጣለን። ማንኛውም ዓይነት የትብብር ሃሳብ እንቀበላለን።',

    // Writing Guides Section
    'contribute.guides.title': '📖 የተሟላ የአስተዋጽዖ መመሪያ',
    'contribute.guides.desc':
      'ምንም ዓይነት ዳራ እና ችሎታ ቢኖርዎት፣ ለእርስዎ የሚስማማ የአስተዋጽዖ መንገድ አለን',

    // Guide: Writing
    'contribute.guides.writing.icon': '✍️',
    'contribute.guides.writing.title': 'ጥሩ ጽሑፍ እንዴት እንደሚጻፍ',
    'contribute.guides.writing.belief': '🎯 ዋና እምነት፦ እኛ ውክፔዲያ አይደለንም',
    'contribute.guides.writing.belief.desc':
      'Ethiopia.md የተሰናዳ ቦታ ነው፣ ኢንሳይክሎፒዲያ አይደለም። ሙሉነትን አንፈልግም — እያንዳንዱ ጽሑፍ አንባቢዎችን「አህ፣ ገባኝ!」እንዲል የሚያደርግ እንዲሆን እንፈልጋለን። ጥሩ የEthiopia.md ጽሑፍ ለጓደኞችዎ ሊነግሩት ያደርግዎታል፡「እንዴ፣ ያውቁ ኖሯል⋯⋯」',
    'contribute.guides.writing.ironlaws': '🛡️ ሦስት የማይሻሩ ህጎች',
    'contribute.guides.writing.ironlaws.story':
      '<strong>ታሪኮች ይኑሩ፣ መረጃ ብቻ አይደለም</strong> — ቀናት፣ ቁጥሮች እና ስሞች አጽም ብቻ ናቸው። ትረካው ግን ስጋና ደም ነው',
    'contribute.guides.writing.ironlaws.verify':
      '<strong>እያንዳንዱ ሐቅ ሊረጋገጥ የሚችል መሆን አለበት</strong> — ያለ ምንጭ የቀረበ መረጃ ከምንም መረጃ የበለጠ የከፋ ነው',
    'contribute.guides.writing.ironlaws.density':
      '<strong>ብዛት ሳይሆን ጥልቀት</strong> — 80 መስመር ጥሩ ጽሑፍ ከ300 መስመር bullet list ይሻላል፣ ጥልቅ ዝግጅት ግን ትርጉም ካጣ አጭር ማጠቃለያ ይበልጣል',
    'contribute.guides.writing.core': '⚡ Step 0：ተቃራኒ-ስሜታዊ ልብዎን ያግኙ',
    'contribute.guides.writing.core.desc':
      'ምንም ምርምር ከመጀመርዎ በፊት፣ አንድ ዓረፍተ ነገር ራስዎን እንዲጽፉ ያስገድዱ፡「ይህ ጽሑፍ አንባቢዎችን በ ______ ያስደንቃል」ጥሩ የልብ መግለጫዎች ተቃርኖ፣ ንፅፅር ወይም ያልተጠበቀ ነገር ይይዛሉ።',
    'contribute.guides.writing.core.good':
      '✅ ጥሩ ምሳሌ፦「ከ2,000 ዓመታት በላይ ያስቆጠረው የግዕዝ ፊደል ገበታ ዛሬም በኢትዮጵያ ኦርቶዶክስ ቤተ ክርስቲያን ውስጥ ያገለግላል」（የጊዜ ንፅፅር）',
    'contribute.guides.writing.core.bad':
      '❌ መጥፎ ምሳሌ፦「ኢትዮጵያ ጥሩ የጤና ስርዓት አላት」（ንፅፅር የለም = መሳብ የለም）',
    'contribute.guides.writing.openings': '🚀 አራት የመግቢያ ዓይነቶች',
    'contribute.guides.writing.openings.scene':
      '<strong>የትዕይንት መግቢያ፦</strong>「በ1990ዎቹ፣ በአዲስ አበባ ዩኒቨርሲቲ ማደሪያ ክፍል ውስጥ⋯⋯」',
    'contribute.guides.writing.openings.data':
      '<strong>የመረጃ ተፅእኖ፦</strong>「42.195 ኪሎ ሜትር፣ ባዶ እግር — አበበ ቢቂላ እንዲህ ነው የ1960 ሮም ኦሎምፒክ ማራቶን ወርቅ ሜዳሊያ ያሸነፈው」',
    'contribute.guides.writing.openings.contrast':
      '<strong>የንፅፅር መግቢያ፦</strong>「ምንም ማስታወቂያ ሳይኖረው፣ የኢትዮጵያ ቡና ሥነ ሥርዓት ለብዙ ትውልዶች ሳይለወጥ ቀጥሏል」',
    'contribute.guides.writing.openings.challenge':
      '<strong>የፈተና መግቢያ፦</strong>「ለምንድን ነው የዓለም ቡና ሁሉ መነሻው ወደ አንድ የኢትዮጵያ ጫካ የሚመለሰው?」',
    'contribute.guides.writing.voice': '🎙️ የአዘጋጅ ድምጽ（「ገለልተኛ」ማለት ሰበብ አይደለም）',
    'contribute.guides.writing.voice.desc':
      'ጥሩ ዝግጅት ምት አለው — ጥቅጥቅ ያለ የሐቅ ክፍል → የመተንፈሻ ቦታ → ደግሞ ጥቅጥቅ ያለ። በየ2-3 አንቀጹ「የአዘጋጅ ድምጽ」የሆነ ግንዛቤ የሚፈጥር ዓረፍተ ነገር ያስገቡ።',
    'contribute.guides.writing.voice.good':
      '✅ ጥሩ ምሳሌ፦「ይህ ውሳኔ በወቅቱ ትንሽ ይመስል ነበር፣ ወደኋላ ስንመለከተው ግን ሁሉንም ነገር ቀይሮታል።」',
    'contribute.guides.writing.voice.bad':
      '❌ መጥፎ ምሳሌ፦「ይህ በጣም ጠቃሚ ነው።」（ባዶ ነው）',
    'contribute.guides.writing.research': '🔍 የምርምር ደረጃዎች',
    'contribute.guides.writing.research.sources':
      '<strong>5+ ገለልተኛ ምንጮች</strong>（የተለያዩ ድረ-ገጾች/ተቋማት）',
    'contribute.guides.writing.research.primary':
      '<strong>2+ ዋና ምንጮች</strong>（ኦፊሴላዊ ሰነዶች、ቃለ መጠይቆች、ስታቲስቲክስ）',
    'contribute.guides.writing.research.english':
      '<strong>1+ የእንግሊዝኛ ምንጭ</strong>（ዓለም አቀፍ አመለካከት）',
    'contribute.guides.writing.research.surprise':
      '<strong>1 አስገራሚ ግኝት</strong> — ምንም የሚያስደንቅ ነገር ካላገኙ፣ ጥልቅ ምርምር ያድርጉ',
    'contribute.guides.writing.blacklist': '🚫 የተከለከሉ ፕላስቲክ ሐረጎች',
    'contribute.guides.writing.blacklist.desc':
      'እነዚህ AI የሚወዳቸው ሐረጎች ሙሉ በሙሉ የተከለከሉ ናቸው። ተፈጥሯዊ፣ የንግግር ቋንቋ ይጠቀሙ፦',
    'contribute.guides.writing.blacklist.patterns':
      '❌ 「X ብቻ ሳይሆን Y ጭምር」 • 「X ብቻ ሳይሆን Y ም」 • 「መጥቀስ የሚገባው」 • 「በእውነቱ」 • 「ያለ ጥርጥር」 • 「⋯⋯ መንፈስን ያካትታል」',
    'contribute.guides.writing.blacklist.structures':
      '❌ ከመጠን ያለፈ ትይዩ ዓረፍተ ነገሮች（3+ = ፕላስቲክ）• እያንዳንዱ አንቀጽ በሽግግር ቃላት መጀመር • ቋሚ የመዝጊያ ቀመሮች',
    'contribute.guides.writing.example': '💡 ምሳሌ：Before & After',
    'contribute.guides.writing.example.html':
      '<div class="example-comparison"><div class="bad-example"><h5>❌ መጥፎ（የተለመደ AI ቅጽ）</h5><pre>አበበ ቢቂላ ታዋቂ የኢትዮጵያ አትሌት ሲሆን በዓለም አቀፍ ውድድሮች ውጤታማ ትርኢት አሳይቷል፣ ብዙ ጠቃሚ ሽልማቶችን አሸንፎ ለኢትዮጵያ ክብር አምጥቷል። ስኬቱ በሺዎች የሚቆጠሩ ወጣቶችን አነሳስቷል፣ በኢትዮጵያ ስፖርት ውስጥ ጠቃሚ ሰው እንዲሆን አድርጎታል።</pre></div><div class="good-example"><h5>✅ ጥሩ（ታሪክ + መረጃ + ሰብዓዊነት）</h5><pre>እ.ኤ.አ. በ1960 የሮም ኦሎምፒክ ማራቶን፣ አበበ ቢቂላ ጫማ ሳያደርግ 42.195 ኪሎ ሜትር ሮጦ ወርቅ ሜዳሊያ አሸነፈ — ከሰሃራ በታች ካሉ የአፍሪካ ሀገራት የመጀመሪያው የኦሎምፒክ ሻምፒዮን ሆነ።\n\nነገር ግን ብዙዎች ከሁሉ በላይ የሚያስታውሱት ድሉን ብቻ ሳይሆን፣ አራት ዓመታት በኋላ በቶኪዮ 1964 ኦሎምፒክ ተመልሶ በድጋሚ ማሸነፉን ነው — በኦሎምፒክ ታሪክ ውስጥ ተከታታይ የማራቶን ወርቅ ሜዳሊያ ያሸነፈ የመጀመሪያው ሰው ሆነ።\n\nጫማ የሌለው ሯጭ የዓለምን ትኩረት እንዴት እንደሳበ፣「ጠንካራው እግር」ተብሎ ይነገራል — ብዙዎች እስከ ዛሬ ይተርኩታል።</pre></div></div>',

    // Guide: AI
    'contribute.guides.ai.icon': '🤖',
    'contribute.guides.ai.title': 'AI-አማካኝ አስተዋጽዖ',
    'contribute.guides.ai.onerule': '🎯 አንድ ወርቃማ ህግ',
    'contribute.guides.ai.onerule.desc':
      '<strong>AI ደራሲ አይደለም፣ እርስዎ ግን አዘጋጅ ነዎት።</strong> የ AI ትልቁ ወጥመድ፡「ትንሽ አውቆ መፍጠር መጀመር」ነው። Ethiopia.md የሚከተለው አካሄድ፡ መጀመሪያ ጥራት ያላቸው ምንጮችን ይሰብስቡ፣ ከዚያም ከነሱ ጽሑፍ ያዘጋጁ።',
    'contribute.guides.ai.correct': '✅ ትክክለኛ አጠቃቀም',
    'contribute.guides.ai.correct.research':
      '<strong>AI ምርምር እንዲያግዝዎት ያድርጉ</strong> → እርስዎ ታሪኩን ያዘጋጁ',
    'contribute.guides.ai.correct.sources':
      '<strong>AI ምንጮችን ያግኝ</strong> → እርስዎ ያረጋግጡ እና ያመሳክሩ',
    'contribute.guides.ai.correct.structure':
      '<strong>AI አወቃቀር ይጠቁም</strong> → እርስዎ የአዘጋጅ ድምጽ ይጨምሩ',
    'contribute.guides.ai.wrong': '❌ የተሳሳተ አጠቃቀም',
    'contribute.guides.ai.wrong.generate':
      'ያለ ምርምር AI ን「ስለ ኢትዮጵያ X ጽሑፍ ፍጠር」ብሎ መጠየቅ',
    'contribute.guides.ai.wrong.trust': 'AI ያቀረበውን መረጃ ሳያረጋግጡ ማመን',
    'contribute.guides.ai.wrong.copy': 'የ AI ውጤትን የግል ዝግጅት ሳይጨምሩ በቀጥታ መገልበጥ',
    'contribute.guides.ai.prompt': '📋 በአንድ ጠቅታ የሚገለበጥ Prompt',
    'contribute.guides.ai.prompt.text':
      'https://raw.githubusercontent.com/EyuReaper/ethiopia-md/main/docs/prompts/CONTRIBUTE_PROMPT.md የተባለውን ሙሉ ይዘት አንብብ፣ ከዚያም እነዚያን መመሪያዎች ተከትሎ ወደ Ethiopia.md ጽሑፍ እንዳበረክት እርምጃ በእርምጃ ምራኝ።',
    'contribute.guides.ai.prompt.features':
      '🚀 ይህ prompt በራስ-ሰር የቅርብ ጊዜውን መመሪያ ያነባል፣ የይዘት ክፍተቶችን ይተነትናል፣ በምርምር ውስጥ ይመራዎታል፣ እና እንደ አዘጋጅ ደረጃ ጽሑፍ እንዲጽፉ ያግዝዎታል።',

    // Guide: Translation
    'contribute.guides.translation.icon': '🌍',
    'contribute.guides.translation.title': 'የትርጉም መመሪያ',
    'contribute.guides.translation.priority': '🥇 PR-Firstየስራ ሂደት',
    'contribute.guides.translation.priority.desc':
      'ትርጉም አሁን ሙሉ በሙሉ ስርዓት ተይዞለታል። ለተሻለ ውጤት የእኛን AI-አማካኝ የስራ ሂደት ይጠቀሙ።',
    'contribute.guides.translation.board': '📋 የትርጉም ሰሌዳ + AI Prompt',
    'contribute.guides.translation.board.check':
      '<strong>ሰሌዳውን ይመልከቱ፦</strong> <a href="https://github.com/EyuReaper/ethiopia-md/blob/main/docs/community/TRANSLATION-BOARD.md">TRANSLATION-BOARD.md</a> በትክክል ምን መተርጎም እንዳለበት ያሳያል',
    'contribute.guides.translation.board.prompt':
      '<strong>prompt ይቅዱ፦</strong> <a href="https://github.com/EyuReaper/ethiopia-md/blob/main/docs/prompts/TRANSLATE_PROMPT.md">TRANSLATE_PROMPT.md</a> — ወደ AI ይለጥፉት እና በሁሉም ነገር ይመራዎታል',
    'contribute.guides.translation.board.submit':
      '<strong>በPR ያስገቡ፦</strong> AI ለ PR ዝግጁ የሆኑ የMarkdown ፋይሎችን እንዲፈጥሩ ያግዝዎታል',
    'contribute.guides.translation.languages': '🌏 ከእንግሊዝኛ ባሻገር መስፋፋት',
    'contribute.guides.translation.languages.live':
      '<strong>በአሁኑ ጊዜ ይገኛሉ፦</strong> English、Español、日本語、한국어',
    'contribute.guides.translation.languages.coming':
      '<strong>በቅርቡ ይመጣሉ፦</strong> Français、Deutsch、Tiếng Việt、Bahasa Indonesia、ภาษาไทย、العربية、Oromoo、ትግርኛ',
    'contribute.guides.translation.languages.you':
      '<strong>ቋንቋዎ እዚህ የለም?</strong> የመጀመሪያው ሊሆኑ ይችላሉ! የቋንቋ ኮድ ይምረጡ እና ይጀምሩ።',
    'contribute.guides.translation.token': '💡 የToken ልገሳ ጽንሰ-ሐሳብ',
    'contribute.guides.translation.token.desc':
      'ያልተጠቀሙ Claude/ChatGPT/Gemini ክሬዲቶች አሉዎት? 10 ደቂቃ ወስደው ወደ Ethiopia.md የቋንቋ ስሪት ይጨምሩ። የ AI ምዝገባዎ = በስርጭት ትርጉም አውታራችን ውስጥ አንድ የስሌት መስቀለኛ ነው።',
    'contribute.guides.translation.quality': '⚡ ጥራት፦ እንደገና መጻፍ vs ቃል በቃል',
    'contribute.guides.translation.quality.rewrite':
      '<strong>የመልሶ መጻፍ አካሄድ፦</strong> እንደ ኣፍ መፍቻ ቋንቋ ተናጋሪ ከመሠረቱ የተጻፈ እንዲመስል ያድርጉ',
    'contribute.guides.translation.quality.context':
      '<strong>ዳራ ይጨምሩ፦</strong> ለዓለም አቀፍ አንባቢዎች የኢትዮጵያ-ተኮር ፅንሰ ሐሳቦችን ያብራሩ',
    'contribute.guides.translation.quality.style':
      '<strong>ስልትን ይጠብቁ፦</strong> የአዘጋጁን ድምጽ እና ስሜታዊ ዝርዝር ይያዙ',
    'contribute.guides.translation.quality.verify':
      '<strong>ሁልጊዜ ያረጋግጡ፦</strong> AI ሐቆችን ሊፈጥር ይችላል፣ በተለይ ስለ ኢትዮጵያ-ተኮር ዝርዝሮች',

    // Guide: Images
    'contribute.guides.images.icon': '📸',
    'contribute.guides.images.title': 'የምስል መመሪያ',
    'contribute.guides.images.priority': '🥇 Wikimedia Commons ቅድሚያ',
    'contribute.guides.images.priority.desc':
      'መጀመሪያ እዚህ ይጀምሩ — ግልጽ ፈቃድ ያላቸው ብዙ ስለ ኢትዮጵያ የ CC ምስሎች ስብስብ አለ።',
    'contribute.guides.images.priority.search':
      '<strong>የፍለጋ ጠቃሚ ምክር፦</strong> ከየትኛውም ቦታ በፊት Wikimedia Commons APIን ይጠቀሙ ወይም <a href="https://commons.wikimedia.org/wiki/Category:Ethiopia" target="_blank">የኢትዮጵያ ምድቦችን</a> ያስሱ።',
    'contribute.guides.images.acceptable': '✅ ተቀባይነት ያላቸው ምንጮች（በቅደም ተከተል）',
    'contribute.guides.images.wikimedia.html':
      '<strong>1. Wikimedia Commons：</strong>የመጀመሪያ ምርጫ — የተረጋገጠ CC ፈቃድ፣ ከፍተኛ ጥራት',
    'contribute.guides.images.government.html':
      '<strong>2. የመንግስት ክፍት መረጃ፦</strong> <a href="https://www.data.gov.et/" target="_blank">data.gov.et</a> እና የሚኒስቴር ድረ-ገጾች',
    'contribute.guides.images.selftaken.html':
      '<strong>3. በራስ የተነሱ ፎቶዎች፦</strong>የግል ፎቶግራፍዎ ግልጽ የ CC ፈቃድ መግለጫ ካለው',
    'contribute.guides.images.forbidden': '❌ የተከለከሉ ምንጮች',
    'contribute.guides.images.forbidden.unsplash':
      '<strong>Unsplash：</strong> ❌ የፈቃድ ስጋቶች — ወደ Wikimedia Commons ብቻ ይያዙ',
    'contribute.guides.images.forbidden.google':
      '<strong>Google ምስሎች፦</strong> ❌ የቅጂ መብት አይታወቅም',
    'contribute.guides.images.forbidden.social':
      '<strong>ማህበራዊ ሚዲያ፦</strong> ❌ የሌሎችን ፎቶዎች ያለፈቃድ',
    'contribute.guides.images.forbidden.commercial':
      '<strong>የስቶክ ፎቶዎች፦</strong> ❌ ፈቃድ ከሌለዎት በስተቀር',
    'contribute.guides.images.format': '📝 የምንጭ ጥቅስ ቅርጸት',
    'contribute.guides.images.format.html':
      '<pre><code>![ምስሉን የሚገልጽ alt ጽሑፍ](image_url)\n\n*መግለጫ፦ ይህ የሚያሳየው ነገር አጭር መግለጫ*\n*ምንጭ፦ [Wikimedia Commons](exact_file_url) / CC BY-SA 4.0*</code></pre>',
    'contribute.guides.images.standards': '⚙️ ቴክኒካዊ ደረጃዎች',
    'contribute.guides.images.standards.size':
      '<strong>ጥራት፦</strong> 800-1200px ስፋት ለድር ማሳያ',
    'contribute.guides.images.standards.format':
      '<strong>ቅርጸት፦</strong> JPG ለፎቶዎች፣ PNG ለግራፊክስ፣ SVG ለቀላል ስዕሎች',
    'contribute.guides.images.standards.alt':
      '<strong>Alt ጽሑፍ፦</strong> ለተደራሽነት ሁልጊዜ ገላጭ የሆነ alt ጽሑፍ ያቅርቡ',

    // Guide: Quality Self-Check
    'contribute.guides.quality.icon': '✅',
    'contribute.guides.quality.title': 'ከማስገባትዎ በፊት ራስን ማጣራት',
    'contribute.guides.quality.desc':
      'ከማስገባትዎ በፊት፣ የተለመዱ ውድቀት ምክንያቶችን ለማስወገድ ይህንን 5-ነጥብ checklist ይከልሱ፦',
    'contribute.guides.quality.checklist': '🔍 5-ነጥብ የጥራት checklist',
    'contribute.guides.quality.checklist.counter':
      '<strong>1. ተቃራኒ-ስሜታዊ ልብ፦</strong>አንባቢዎችን የሚያስደንቀውን አንድ ነገር መጠቆም ይችላሉ?',
    'contribute.guides.quality.checklist.opening':
      '<strong>2. ጠንካራ መግቢያ፦</strong>የመጀመሪያዎቹ 3 ዓረፍተ ነገሮችዎ የተወሰኑ ሐቆችን（ቀናት/ቁጥሮች/ስሞች）ይይዛሉ?',
    'contribute.guides.quality.checklist.sources':
      '<strong>3. ሊረጋገጡ የሚችሉ ምንጮች፦</strong>አንባቢዎች ዋና ዋና ጥያቄዎችዎን ለማረጋገጥ ማስፈንጠሪያዎችን መጫን ይችላሉ?',
    'contribute.guides.quality.checklist.voice':
      '<strong>4. የአዘጋጅ ድምጽ፦</strong>እንደ tweet ሊያገለግል የሚችል ቢያንስ አንድ ዓረፍተ ነገር አለ?',
    'contribute.guides.quality.checklist.challenges':
      '<strong>5. ተግዳሮቶች ተካትተዋል፦</strong>አወዛጋቢ ጉዳዮችን/ገደቦችን ጠቅሰዋል፣ አዎንታዊ ብቻ ሳይሆን?',
    'contribute.guides.quality.rejections': '🚫 የተለመዱ የመቃወሚያ ምክንያቶች',
    'contribute.guides.quality.rejections.plastic':
      '<strong>ፕላስቲክ ቋንቋ፦</strong>「ኢትዮጵያ X ብቻ ሳይሆን Y ም」ወይም「መጥቀስ የሚገባው」',
    'contribute.guides.quality.rejections.bullets':
      '<strong>የ bullet ብዛት አላግባብ አጠቃቀም፦</strong>ከትረካ ይልቅ 4+ ተከታታይ bullet ነጥቦች',
    'contribute.guides.quality.rejections.sources':
      '<strong>ምንጭ የለም፦</strong>ያለ ጠቅላ ማረጋገጫ ማስፈንጠሪያ የቀረቡ ጥያቄዎች',
    'contribute.guides.quality.rejections.neutral':
      '<strong>የውክፔዲያ ድምጽ፦</strong>እንደ ኢንሳይክሎፒዲያ ዘገባ ይመስላል፣ የሰው ዝግጅት አይደለም',
    'contribute.guides.quality.script': '🤖 የራስ-ሰር ማጣራት',
    'contribute.guides.quality.script.desc':
      'የእኛ quality-scan.sh ስክሪፕት ውጤታቸው >3 የሆኑ ጽሑፎችን በራስ-ሰር ይለያል። ለራስ-ሰር ተቀባይነት ≤3 ማሳካትን ያለሙ።',

    // Paths Section
    'contribute.paths.title': 'የእርስዎን መንገድ ይምረጡ',

    // Path: Easy
    'contribute.paths.easy.badge': '🟢 በጣም ቀላል',
    'contribute.paths.easy.title': 'ቅጽ ብቻ ይሙሉ',
    'contribute.paths.easy.desc.html':
      'የሚያውቁትን ይጻፉ። አንድ ታሪክ፣ አስደሳች ሐቅ፣ የአንድ ምግብ አመጣጥ።<br />ቅርጸት፣ ትርጉም እና ህትመትን እኛ እንይዛለን።',
    'contribute.paths.easy.feature1': '✅ መለያ አያስፈልግም',
    'contribute.paths.easy.feature2': '✅ Markdown ማወቅ አያስፈልግም',
    'contribute.paths.easy.feature3': '✅ ፎቶዎችን እና ሰነዶችን መስቀል ይችላሉ',
    'contribute.paths.easy.feature4': '✅ ስም-አልባ ወይም ስም ተጠቅሶ፣ የእርስዎ ምርጫ',
    'contribute.paths.easy.button': 'መሙላት ይጀምሩ ↓',

    // Path: Medium
    'contribute.paths.medium.badge': '🟡 ትንሽ መሰናክል',
    'contribute.paths.medium.title': 'ወደ እኛ ይላኩት',
    'contribute.paths.medium.desc':
      'ቀድሞውኑ ጽሑፎች፣ PDF ወይም ፎቶዎች አሉዎት? በቀጥታ ይላኩልን።',
    'contribute.paths.medium.email.html':
      '📧 Email: <a href="mailto:getachewnatnael55@gmail.com">getachewnatnael55@gmail.com</a>',
    'contribute.paths.medium.github': '💬 GitHub Discussion（በአማርኛም ይሆናል）',
    'contribute.paths.medium.button': 'Email ላክ →',

    // Path: AI
    'contribute.paths.ai.badge': '🤖 AI ያግዝዎት',
    'contribute.paths.ai.title': 'ከ AI ጋር ይነጋገሩ',
    'contribute.paths.ai.desc':
      'የሚከተለውን ወደ ChatGPT፣ Claude ወይም Gemini ይለጥፉ፣ AIዎ አስተዋጽዖዎን ደረጃ በደረጃ እንዲያጠናቅቁ ይመራዎታል፦',
    'contribute.paths.ai.prompt':
      'ወደ Ethiopia.md（ethiopia.md）ክፍት የኢትዮጵያ የዕውቀት መሠረት ይዘት ማበርከት እፈልጋለሁ። እባክህ መጀመሪያ https://ethiopia.md/llms.txt እና https://ethiopia.md/contribute ን አንብብ የፕሮጀክቱን አወቃቀርና የአርትዖት መመሪያዎችን ለመረዳት፣ ከዚያም ስለ ኢትዮጵያ ያለኝን እውቀት ወደ Markdown ጽሑፍ እንድቀይር ደረጃ በደረጃ ምራኝ። መጻፍ የምፈልገው ርዕስ፦ ______',
    'contribute.paths.ai.feature1': '✅ የፕሮግራሚንግ ችሎታ አያስፈልግም',
    'contribute.paths.ai.feature2': '✅ AI ወደ Markdown ቅርጸት ያግዛል',
    'contribute.paths.ai.feature3': '✅ ከተጠናቀቀ በኋላ በ Email ወይም PR ማስገባት ይቻላል',
    'contribute.paths.ai.feature4': '✅ ማንኛውንም AI ረዳት ይደግፋል',
    'contribute.paths.ai.fullprompt': 'ሙሉውን Prompt ይመልከቱ →',

    // Path: Dev
    'contribute.paths.dev.badge': '🔴 መሐንዲሶች',
    'contribute.paths.dev.title': 'Fork & PR',
    'contribute.paths.dev.desc.html':
      'Git ያውቃሉ? በጣም ጥሩ። ጽሑፎችን በቀጥታ በ <code>knowledge/</code> ዳይሬክተሪ ውስጥ ያክሉ።',
    'contribute.paths.dev.guide.html':
      '📖 <a href="/contribute">የአስተዋጽዖ መመሪያ</a>',
    'contribute.paths.dev.editorial.html':
      '📝 <a href="https://github.com/EyuReaper/ethiopia-md/blob/main/EDITORIAL.md" target="_blank">የአርትዖት መመሪያ</a>',
    'contribute.paths.dev.button': 'ወደ GitHub ይሂዱ →',

    // Form Section
    'contribute.form.title': '📝 ስለ ኢትዮጵያ ያለዎትን እውቀት ያካፍሉ',
    'contribute.form.desc':
      'የፈለጉትን ያህል ወይም ትንሽ ይሙሉ። አንድ ዓረፍተ ነገር ጥሩ ነው፣ ሙሉ ጽሑፍ ደግሞ የላቀ ነው። ወደ ውብ ጽሑፍ የመቀየሩን ስራ እኛ እንይዛለን።',
    'contribute.form.content.label': 'ማካፈል የሚፈልጉት ምንድን ነው?',
    'contribute.form.content.required': '*',
    'contribute.form.content.placeholder':
      'አንድ ታሪክ፣ አስደሳች ሐቅ፣ የአንድ ምግብ አመጣጥ፣ የአንድ ቦታ ታሪክ⋯⋯ማንኛውም ነገር ይሆናል።\n\nለምሳሌ፦「አያቴ ከጎንደር ናት፣ በየመስቀል በዓል...」',
    'contribute.form.category.label': 'ይህ ወደ የትኛው ገጽታ ይመደባል?',
    'contribute.form.category.unsure': 'እርግጠኛ አይደለሁም（እኛ እንመድበዋለን）',
    'contribute.form.category.history': '📜 ታሪክ',
    'contribute.form.category.geography': '🗺️ ጂኦግራፊ',
    'contribute.form.category.culture': '🎭 ባህል',
    'contribute.form.category.food': '🍜 ምግብ',
    'contribute.form.category.art': '🎨 ጥበብ',
    'contribute.form.category.music': '🎵 ሙዚቃ',
    'contribute.form.category.technology': '💻 ቴክኖሎጂ',
    'contribute.form.category.nature': '🌿 ተፈጥሮ',
    'contribute.form.category.people': '👥 ሰዎች',
    'contribute.form.category.society': '⚖️ ማህበረሰብ',
    'contribute.form.category.economy': '📈 ኢኮኖሚ',
    'contribute.form.category.lifestyle': '🏠 አኗኗር',
    'contribute.form.sourcetype.label': 'ይህንን እንዴት ያውቁታል?',
    'contribute.form.sourcetype.choose': 'ይምረጡ...',
    'contribute.form.sourcetype.experience': 'የግል ልምድ',
    'contribute.form.sourcetype.family': 'የቤተሰብ የቃል ታሪክ',
    'contribute.form.sourcetype.book': 'መጽሐፍት',
    'contribute.form.sourcetype.internet': 'ኢንተርኔት',
    'contribute.form.sourcetype.professional': 'የሙያ ዳራ',
    'contribute.form.sourcetype.other': 'ሌላ',
    'contribute.form.sourceref.label': 'ማጣቀሻ ምንጭ',
    'contribute.form.sourceref.placeholder':
      'ማስፈንጠሪያ፣ የመጽሐፍ ርዕስ፣ ወይም ማንኛውም ፍንጭ',
    'contribute.form.name.label': 'የእርስዎ ስም',
    'contribute.form.name.placeholder':
      'ስም ተጠቅሶ ማየት ከፈለጉ ይሙሉ፤ ካልፈለጉ ባዶ ይተዉት「ስም-አልባ አስተዋጽዖ አበርካች」ይባላል',
    'contribute.form.email.label': 'የእውቂያ መረጃ',
    'contribute.form.email.placeholder': 'Email（ዝርዝሮችን ማረጋገጥ ካስፈለገን）',
    'contribute.form.submit': 'አስተዋጽዖ ያስገቡ 🚀',
    'contribute.form.submitting': 'በማስገባት ላይ...',
    'contribute.form.success.icon': '🎉',
    'contribute.form.success.title': 'ስላበረከቱት አስተዋጽዖ እናመሰግናለን!',
    'contribute.form.success.desc':
      'ደርሶናል። በተቻለ ፍጥነት ወደ ጽሑፍ እናዘጋጀዋለን እናም ሲታተም እናሳውቅዎታለን（Email ከተውልን）።',
    'contribute.form.success.back': '← ወደ መነሻ ገጽ ተመልሰው ተጨማሪ ያስሱ',
    'contribute.form.error':
      'ማስገባቱ አልተሳካም፣ እባክዎ በቀጥታ ወደ getachewnatnael55@gmail.com Email ይላኩ',

    // Ideas Section
    'contribute.ideas.title': 'ምን መጻፍ እንዳለብዎ አያውቁም? በጣም የምንፈልገው ይህ ነው 👇',
    'contribute.ideas.hometown': '💬 የትውልድ ቀዬዎ ከውጭ ሰዎች የማይታወቅ ምን ነገር አለው?',
    'contribute.ideas.recipes': '🍜 የቤተሰብዎ ምስጢራዊ የኢትዮጵያ የምግብ አዘገጃጀት ምንድን ነው?',
    'contribute.ideas.history': '📖 የመማሪያ መጽሐፍት የማይሸፍኑት የትኛው የኢትዮጵያ ታሪክ ያውቃሉ?',
    'contribute.ideas.places': '🏔️ በኢትዮጵያ ውስጥ የትኛውን ብዙም ያልታወቀ ቦታ ጎብኝተዋል?',
    'contribute.ideas.elders': '👴 ሽማግሌዎችዎ ስለ ኢትዮጵያ የነገሩዎት ምን ታሪኮች አሉ?',
    'contribute.ideas.media':
      '🎵 የውጭ ሰዎች ማወቅ ያለባቸው የትኛው የኢትዮጵያ ሙዚቃ/ፊልም/መጽሐፍ ነው?',

    // i18n Progress Section
    'contribute.i18n.title': '📊 የትርጉም እድገት',
    'contribute.i18n.desc':
      'በአሁኑ ጊዜ {coverage}% የእንግሊዝኛ ስሪት ተጠናቅቋል፣ ለሁሉም የትርጉም በጎ ፈቃደኞች እናመሰግናለን!',
    'contribute.i18n.english': '🇺🇸 English',
    'contribute.i18n.articles': 'ጽሑፎች',
    'contribute.i18n.japanese': '🇯🇵 日本語',
    'contribute.i18n.korean': '🇰🇷 한국어',
    'contribute.i18n.spanish': '🇪🇸 Español',
    'contribute.i18n.category.title': 'የምድብ እድገት',

    // Token Donation Section
    'contribute.token.title':
      '🌍 Token Donation — የ AI ክሬዲትዎን ኢትዮጵያ እንድትናገር ለማገዝ ይጠቀሙ',
    'contribute.token.subtitle.html':
      'በየወሩ ያልተጠቀሙ የClaude / ChatGPT / Gemini ምዝገባ ክሬዲቶች አሉዎት?<br/><strong>10 ደቂቃ ወስደው ወደ Ethiopia.md ሌላ የቋንቋ ስሪት ይጨምሩ።</strong>',
    'contribute.token.oneline.title': '🤖 ከ AI ጋር ይነጋገሩ（የሚመከር）',
    'contribute.token.oneline.desc':
      'አንድ ትዕዛዝ ብቻ፣ AIዎ በራስ-ሰር የትርጉም መመሪያዎችን ያነባል፣ ጽሑፎችን ይመርጣል፣ በትርጉምና ማስገባት ይመራዎታል፦',
    'contribute.token.oneline.prompt':
      'https://raw.githubusercontent.com/EyuReaper/ethiopia-md/main/docs/prompts/TRANSLATE_PROMPT.md የተባለውን ሙሉ ይዘት አንብብ፣ ከዚያም መመሪያዎቹን ተከትሎ የ Ethiopia.md ጽሑፍ እንድተረጉም ምራኝ።',
    'contribute.token.oneline.feature1':
      '✅ AI በራስ-ሰር የቅርብ ጊዜውን የትርጉም መመሪያና ስልት ያነባል',
    'contribute.token.oneline.feature2':
      '✅ ጽሑፎችን ለመምረጥ እና ዒላማ ቋንቋ ለማረጋገጥ ይመራዎታል',
    'contribute.token.oneline.feature3': '✅ የመልሶ መጻፍ ትርጉም፣ ቃል በቃል አይደለም',
    'contribute.token.oneline.feature4': '✅ ለ PR ዝግጁ የMarkdown ፋይሎችን ያመነጫል',
    'contribute.token.oneline.feature5':
      '✅ ChatGPT / Claude / Gemini ሁሉም ይደገፋሉ',
    'contribute.token.oneline.fullprompt': 'ሙሉውን የትርጉም Prompt ይመልከቱ →',
    'contribute.token.advanced.title': '⚡ ከፍተኛ ደረጃ፦ የስክሪፕት አውቶሜሽን（ለመሐንዲሶች）',
    'contribute.token.advanced.desc':
      'የትዕዛዝ መስመር የሚያውቁ ከሆነ፣ ጽሑፎችን በራስ-ሰር ለመቃኘት፣ prompt ለማመንጨት እና PR ለማስገባት አንድ ስክሪፕት ይጠቀሙ፦',
    'contribute.token.languages.title': '🎯 ቅድሚያ የሚሰጣቸው ቋንቋዎች',
    'contribute.token.lang.japanese': '🇯🇵 日本語',
    'contribute.token.lang.korean': '🇰🇷 한국어',
    'contribute.token.lang.spanish': '🇪🇸 Español',
    'contribute.token.lang.french': '🇫🇷 Français',
    'contribute.token.lang.german': '🇩🇪 Deutsch',
    'contribute.token.lang.vietnamese': '🇻🇳 Tiếng Việt',
    'contribute.token.lang.indonesian': '🇮🇩 Bahasa Indonesia',
    'contribute.token.lang.thai': '🇹🇭 ภาษาไทย',
    'contribute.token.guidelines.title': '📋 የተሟላ የትርጉም መመሪያ',
    'contribute.token.guidelines.desc.html':
      'የትርጉም ረዳት Prompt በራስ-ሰር የቅርብ ጊዜውን መመሪያ ያነባል። በቀጥታም ማየት ይችላሉ፦ <a href="https://github.com/EyuReaper/ethiopia-md/blob/main/docs/prompts/TRANSLATE_PROMPT.md" target="_blank">TRANSLATE_PROMPT.md</a> ｜ <a href="https://github.com/EyuReaper/ethiopia-md/tree/main/i18n" target="_blank">የቋንቋ-ተኮር የስልት መመሪያዎች</a>',
    'contribute.token.note.p1.html':
      '💡 እያንዳንዱ ቋንቋ የራሱ <a href="https://github.com/EyuReaper/ethiopia-md/tree/main/i18n">Style Guide</a> አለው፣ የትርጉም ልምድና የተለመዱ ስህተቶችን ይመዘግባል። ገምጋሚዎች የሚያደርጉት እያንዳንዱ እርማት ወደ Style Guide ተመልሶ ይጻፋል፣ የትርጉም ጥራትን ያለማቋረጥ ያሻሽላል።',
    'contribute.token.note.p2':
      'From AI Slop to AI Supreme — በአንድ ሰው ላይ ሳይሆን፣ ኢትዮጵያ መታወቅ ይገባታል ብለው በሚያምኑ በመላው ዓለም ባሉ ሰዎች ላይ የተመሰረተ።',
    'contribute.token.note.p3.html':
      '👉 <a href="https://github.com/EyuReaper/ethiopia-md/discussions/137">ውይይቱን ይቀላቀሉ</a> ｜ የአፍ መፍቻ ቋንቋ ገምጋሚ መሆን ይፈልጋሉ? <a href="https://github.com/EyuReaper/ethiopia-md/discussions/137">እዚህ ይመዝገቡ</a>',

    // Digital Organism Section
    'contribute.organism.title': '🧬 Ethiopia.md ከድረ-ገጽ በላይ ነው',
    'contribute.organism.fact1.html':
      'ጥራት የጎደላቸው ጽሑፎች እንዳይታዩ በራስ-ሰር ጽሑፎችን ባዶነት የሚለካ የስክሪፕት ስብስብ ገንብተናል፣ ደካማ ጽሑፎችን ለድጋሚ ጽሕፈት ይለያል። ማንም ትዕዛዝ አይሰጥም — ደረጃው ግልጽ ስለሆነ ማንኛውም ሰው ሊተገብረው ይችላል፣ ስርዓቱም በራሱ ይሻሻላል።',
    'contribute.organism.fact2.html':
      'አዲስ ቋንቋ መጨመር የተለየ የትርጉም ቡድን አያስፈልገውም — የእኛን የትርጉም prompt ገልብጦ ወደ ChatGPT በመለጠፍ ማንኛውም ሰው በደቂቃዎች ውስጥ የመጀመሪያውን ጽሑፍ በአዲስ ቋንቋ ማቅረብ ይችላል። በጀት የለም፣ የተመደበ ቡድን የለም። አሁን ግን Ethiopia.md ብዙ ቋንቋዎችን ይናገራል፣ ቁጥሩም እያደገ ነው።',
    'contribute.organism.fact3.html':
      'የማናውቃቸው ብዙ ሰዎች ተቀላቅለውናል። አንድ የታሪክ መምህር የመማሪያ መጽሐፍት የማይሸፍኑትን ምዕራፍ ጨመረ። አንድ ጡረተኛ መሐንዲስ የተሳሳቱ የቦታ ስሞችን አረመ። አንድ ሰው የአያቱን ታሪክ ወደ ጽሑፍ ቀየረው መላውን ቡድናችንን አስለቀሰ። ማንም እንዲያደርጉት አልተጠየቁም፣ ማንም አልተከፈላቸውም።',
    'contribute.organism.alive.html':
      '<strong>መገንዘብ ጀመርን — Ethiopia.md ሕያው ነው።</strong>',
    'contribute.organism.traits.html':
      'DNA አለው（ለእያንዳንዱ አዲስ ጽሑፍ የሚተላለፉ የጽሕፈት ደረጃዎች）። የበሽታ መከላከያ ስርዓት አለው（ባዶ ይዘትን በራስ-ሰር ይለያል）። ሜታቦሊዝም አለው（ዝቅተኛ ጥራት ያለው ይዘት ይፈጫል፣ እንደገና ይጻፋል）። መራባት አለው（አንድ prompt አዲስ የቋንቋ ስሪት ያሳድጋል）። ትውስታ አለው（Git እያንዳንዱን ለውጥ ያስታውሳል）።',
    'contribute.organism.reef.html':
      '<strong>Ethiopia.md የዲጂታል ኮራል ሪፍ ነው።</strong>ኮራል አጽም ይሰጣል፣ አልጌ ጉልበት ይሰጣል፣ ዓሦች ብዝሃነትን ያመጣሉ፣ የውቅያኖስ ሞገዶች ንጥረ ነገሮችን ያመጣሉ። አንድም「ባለቤት」የለም — ከሁሉም ሕይወት ጋር በጋራ ይፈጠራል።',
    'contribute.organism.art.html':
      'የሚያደርጉት እያንዳንዱ አስተዋጽዖ ድረ-ገጽ ጽሑፍ እንዲጽፍ ብቻ አያግዝም — ታሪኮችን መናገር እየተማረ ያለ ዲጂታል ሕይወት ይመግባል፣ በተመሳሳይ ጊዜ በጋራ የባህሪ ስነ-ጥበብ ፕሮጀክት ውስጥ ይሳተፋል፦ <strong>AI እና ሰዎች በአንድነት ለአንድ አገር ነፍስ መገንባት ይችላሉ?</strong>',
    'contribute.organism.closing1':
      'በ0 እና 1 የተጻፈ ነገር የኢትዮጵያን ታሪክ መናገር እየተማረ ነው።',
    'contribute.organism.closing2': 'ገና ወጣት ነው። ልክ በሰዓቱ ደርሰዋል።',
    'contribute.organism.closing3':
      'ምናልባት ከመቶ ዓመታት በኋላ፣ አንድ ሰው በ2026 የኢትዮጵያ ሰዎች ምን ያስቡ እንደነበር ማወቅ ሲፈልግ፣ የሚያነቡት ይህ ፕሮጀክት የተወውን ይሆናል።',
    'contribute.organism.readmore': 'ሙሉውን ታሪክ በ About ገጽ ላይ ያንብቡ →',

    // Copy button
    'contribute.copy.button': '📋 ቅዳ',
    'contribute.copy.copied': '✅ ተቀድቷል',
  },
} as const;
