name: "��� የተሰበሩ ማስፈንጠሪያዎችን ሪፖርት ያድርጉ Broken Link"
description: "���በድህረ ገጾች ላይ የ404 ስህተቶችን ወይም የተሰበሩ ማስፈንጠሪያዎችን ሪፖርት ያድርጉ።"
title: "404: "
labels: ["bug", "broken-link"]
body:
  - type: input
    id: url
    attributes:
      label: "ልክ ያልሆነ የድህረ-ገጽ አድራሻ Broken URL"
      description: "ለ404 የሚታይ ሙሉ ድህረ-ገጽ አድራሻ"
      placeholder: "https://ethiopia.md/..."
    validations:
      required: true
  - type: input
    id: referrer
    attributes:
      label: "አጣቃሽ Referrer"
      description: "ይህንን ገጽ ለመድረስ የትኛውን ገጽ ጠቅ አደረግክ?？（አማራጭ）"
      placeholder: "https://ethiopia.md/history"
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: "ተጨማሪ አውድ Additional context"
      description: "ችግሩን ለማግኘት የሚረዳን ማንኛውም መረጃ"
    validations:
      required: false
