name: 🐛 Bug ሳንካ / Bug Report
description: የድህረ-ገጽ ተግባራዊነት ችግሮች፣ የማሳያ ስህተቶች፣ የተሰበሩ ማስፈንጠሪያዎች፣ ወዘተ.
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: የችግሩ መግለጫ / Description
      description: ያጋጠመዎትን ችግር እባክዎን ይግለጹ።
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: ችግር ገጽ URL
      placeholder: "https://ethiopia.md/..."
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: ቅፅበተ ፎቶ / Screenshot
      description: ከተቻለ፣ እባክዎን ቅጽበታዊ ፎቶ ያያይዙ።
    validations:
      required: false
